on: [push, pull_request]

jobs:
  test_verify_commit:
    runs-on: ubuntu-latest
    name: Test Verify Commits
    steps:
      - name: Test Verify Commits
        uses: atomiix/verify-commit-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}